[prover]
round_no = 0
batch_size = 1024
hyper_tree_size = 4
user_data_path = "/Users/yangweitao/dev/okx/proof-of-reserves-v2/test-data/user-data/"
num_of_tokens = 156
[db]
level_db_path = "level_db_data"
[log]
file_name_prefix = "zkpor"
dir = "logs/"
level = "debug"
console = false
flame = false