name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODE_COV_VAL: '0'

    steps:
    - name: Clone main repository
      uses: actions/checkout@v4

    - uses: moonrepo/setup-rust@v1
      with:
        components: rustfmt
        cache: false
      name: Setup Rust Toolchain

    - uses: Swatinem/rust-cache@v2
      name: Cache Rust Dependencies

    - run: export RUSTFLAGS="-D warnings" && cargo build
      name: Run build scripts

    - name: Check Format
      run: cargo fmt --check
      working-directory: .

    # - name: Run Tests
    #   run: cargo test --verbose --lib
    #   working-directory: .

    - name: Install dependencies
      run: sudo apt-get install -y musl-tools

    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests with coverage
      run: |
        LAST_LINE = $(cargo tarpaulin --lib --out Html --output-dir target/debug/tarpaulin/ -- --nocapture | tail -n 1)
        export CODE_COV_VAL=$LAST_LINE
        echo "CODE_COV_VAL is $LAST_LINE"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/debug/tarpaulin/
        publish_branch: gh-pages